[package]
name = "mt_web_server"
version = "0.1.0"
authors = ["marcus_oa <marcus.official1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
